/**
 * Cisco IOS 15.x script generator.
 * Pure string generation — zero external dependencies.
 * All output is syntactically correct for paste into an enable/config-mode terminal.
 */

export type CiscoScriptType =
  | 'interface-basic'
  | 'interface-trunk'
  | 'ospf-basic'
  | 'static-routes'
  | 'acl-extended'
  | 'vlan-config'
  | 'dhcp-pool'

export interface InterfaceBasicParams {
  type: 'interface-basic'
  interfaceName: string
  ipAddress: string
  subnetMask: string
  description?: string
  shutdown?: boolean
  duplexAuto?: boolean
  speedAuto?: boolean
}

export interface InterfaceTrunkParams {
  type: 'interface-trunk'
  interfaceName: string
  allowedVlans: number[]
  nativeVlan?: number
  description?: string
}

export interface OSPFBasicParams {
  type: 'ospf-basic'
  processId: number
  networks: Array<{
    network: string
    wildcardMask: string
    area: number
  }>
  routerId?: string
  passiveInterfaces?: string[]
  defaultInformationOriginate?: boolean
}

export interface StaticRoutesParams {
  type: 'static-routes'
  routes: Array<{
    destination: string
    mask: string
    nextHop: string
    adminDistance?: number
    description?: string
  }>
}

export interface ACLExtendedParams {
  type: 'acl-extended'
  name: string
  rules: Array<{
    action: 'permit' | 'deny'
    protocol: 'ip' | 'tcp' | 'udp' | 'icmp'
    source: string
    destination: string
    destinationPort?: string
    remark?: string
  }>
  applyToInterface?: {
    interfaceName: string
    direction: 'in' | 'out'
  }
}

export interface VLANConfigParams {
  type: 'vlan-config'
  vlans: Array<{
    id: number
    name: string
    sviIp?: string
    sviMask?: string
  }>
}

export interface DHCPPoolParams {
  type: 'dhcp-pool'
  pools: Array<{
    name: string
    network: string
    mask: string
    defaultGateway?: string
    dnsServers?: string[]
    domainName?: string
    leaseTime?: { days: number; hours: number; minutes: number }
    excludedRanges?: Array<{ start: string; end: string }>
  }>
}

export type CiscoScriptParams =
  | InterfaceBasicParams
  | InterfaceTrunkParams
  | OSPFBasicParams
  | StaticRoutesParams
  | ACLExtendedParams
  | VLANConfigParams
  | DHCPPoolParams

export interface GeneratedScript {
  title: string
  script: string
  warnings: string[]
  commandCount: number
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function scriptHeader(): string[] {
  return [
    '! Generated by NetTools — nettools.pages.dev',
    `! Date: ${isoDate()}`,
    '!',
  ];
}

function countCommands(script: string): number {
  return script.split('\n').filter(line => {
    const t = line.trim();
    return t.length > 0 && !t.startsWith('!');
  }).length;
}

function build(title: string, lines: string[], warnings: string[]): GeneratedScript {
  const script = lines.join('\n');
  return { title, script, warnings, commandCount: countCommands(script) };
}

function requireNonEmpty(value: string, field: string): void {
  if (!value || !value.trim()) throw new Error(`${field} cannot be empty`);
}

function isNumericName(name: string): boolean {
  const n = Number(name);
  return Number.isInteger(n) && String(n) === name.trim();
}

// ─── Generators ──────────────────────────────────────────────────────────────

function interfaceBasic(p: InterfaceBasicParams): GeneratedScript {
  requireNonEmpty(p.interfaceName, 'interfaceName');
  requireNonEmpty(p.ipAddress, 'ipAddress');
  requireNonEmpty(p.subnetMask, 'subnetMask');

  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
    `interface ${p.interfaceName}`,
  ];

  if (p.description) lines.push(` description ${p.description}`);
  lines.push(` ip address ${p.ipAddress} ${p.subnetMask}`);
  if (p.duplexAuto) lines.push(' duplex auto');
  if (p.speedAuto)  lines.push(' speed auto');
  lines.push(p.shutdown ? ' shutdown' : ' no shutdown');
  lines.push('!');
  lines.push('end');

  return build(`Interface Configuration — ${p.interfaceName}`, lines, []);
}

function interfaceTrunk(p: InterfaceTrunkParams): GeneratedScript {
  requireNonEmpty(p.interfaceName, 'interfaceName');
  if (!p.allowedVlans || p.allowedVlans.length === 0)
    throw new Error('allowedVlans cannot be empty');

  const warnings: string[] = [];
  const nativeVlan = p.nativeVlan ?? 1;

  if (nativeVlan === 1) {
    warnings.push(
      'VLAN 1 is the default native VLAN and a known attack vector (VLAN hopping). ' +
      'Consider setting native VLAN to an unused VLAN ID.'
    );
  }

  const vlanList = [...p.allowedVlans].sort((a, b) => a - b).join(',');

  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
    `interface ${p.interfaceName}`,
  ];

  if (p.description) lines.push(` description ${p.description}`);
  lines.push(' switchport trunk encapsulation dot1q');
  lines.push(' switchport mode trunk');
  lines.push(` switchport trunk allowed vlan ${vlanList}`);
  lines.push(` switchport trunk native vlan ${nativeVlan}`);
  lines.push(' no shutdown');
  lines.push('!');
  lines.push('end');

  return build(`Trunk Interface — ${p.interfaceName}`, lines, warnings);
}

function ospfBasic(p: OSPFBasicParams): GeneratedScript {
  if (!Number.isInteger(p.processId) || p.processId < 1 || p.processId > 65535)
    throw new Error(`OSPF processId must be 1–65535, got ${p.processId}`);
  if (!p.networks || p.networks.length === 0)
    throw new Error('OSPF networks list cannot be empty');

  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
    `router ospf ${p.processId}`,
  ];

  if (p.routerId) lines.push(` router-id ${p.routerId}`);

  for (const net of p.networks)
    lines.push(` network ${net.network} ${net.wildcardMask} area ${net.area}`);

  for (const iface of (p.passiveInterfaces ?? []))
    lines.push(` passive-interface ${iface}`);

  if (p.defaultInformationOriginate) lines.push(' default-information originate');

  lines.push('!');
  lines.push('end');

  return build(`OSPF Process ${p.processId} Configuration`, lines, []);
}

function staticRoutes(p: StaticRoutesParams): GeneratedScript {
  if (!p.routes || p.routes.length === 0)
    throw new Error('routes cannot be empty');

  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
  ];

  for (const route of p.routes) {
    if (route.description) lines.push(`! ${route.description}`);
    const dist = route.adminDistance !== undefined ? ` ${route.adminDistance}` : '';
    lines.push(`ip route ${route.destination} ${route.mask} ${route.nextHop}${dist}`);
  }

  lines.push('!');
  lines.push('end');

  const n = p.routes.length;
  return build(`Static Routes (${n} route${n === 1 ? '' : 's'})`, lines, []);
}

function aclExtended(p: ACLExtendedParams): GeneratedScript {
  requireNonEmpty(p.name, 'ACL name');
  if (!p.rules || p.rules.length === 0)
    throw new Error('ACL rules cannot be empty');

  const numeric = isNumericName(p.name);
  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
  ];

  const portSuffix = (rule: ACLExtendedParams['rules'][number]): string =>
    (rule.protocol === 'tcp' || rule.protocol === 'udp') && rule.destinationPort
      ? ` ${rule.destinationPort}`
      : '';

  if (numeric) {
    for (const rule of p.rules) {
      if (rule.remark)
        lines.push(`access-list ${p.name} remark ${rule.remark}`);
      lines.push(
        `access-list ${p.name} ${rule.action} ${rule.protocol} ` +
        `${rule.source} ${rule.destination}${portSuffix(rule)}`
      );
    }
  } else {
    lines.push(`ip access-list extended ${p.name}`);
    let seq = 10;
    for (const rule of p.rules) {
      if (rule.remark) lines.push(` remark ${rule.remark}`);
      lines.push(
        ` ${seq} ${rule.action} ${rule.protocol} ` +
        `${rule.source} ${rule.destination}${portSuffix(rule)}`
      );
      seq += 10;
    }
  }

  if (p.applyToInterface) {
    lines.push('!');
    lines.push(`interface ${p.applyToInterface.interfaceName}`);
    lines.push(` ip access-group ${p.name} ${p.applyToInterface.direction}`);
  }

  lines.push('!');
  lines.push('end');

  return build(`Extended ACL — ${p.name}`, lines, []);
}

function vlanConfig(p: VLANConfigParams): GeneratedScript {
  if (!p.vlans || p.vlans.length === 0)
    throw new Error('vlans cannot be empty');

  for (const v of p.vlans) {
    if (!Number.isInteger(v.id) || v.id < 1 || v.id > 4094)
      throw new Error(`VLAN ID must be 1–4094, got ${v.id}`);
    requireNonEmpty(v.name, 'vlan name');
  }

  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
  ];

  // VLAN database entries
  for (const vlan of p.vlans) {
    lines.push(`vlan ${vlan.id}`);
    lines.push(` name ${vlan.name}`);
    lines.push('!');
  }

  // SVI interfaces (only for VLANs that have both sviIp and sviMask)
  for (const vlan of p.vlans) {
    if (vlan.sviIp && vlan.sviMask) {
      lines.push(`interface Vlan${vlan.id}`);
      lines.push(` ip address ${vlan.sviIp} ${vlan.sviMask}`);
      lines.push(' no shutdown');
      lines.push('!');
    }
  }

  lines.push('end');

  const n = p.vlans.length;
  return build(`VLAN Configuration (${n} VLAN${n === 1 ? '' : 's'})`, lines, []);
}

function dhcpPool(p: DHCPPoolParams): GeneratedScript {
  if (!p.pools || p.pools.length === 0)
    throw new Error('pools cannot be empty');

  for (const pool of p.pools) requireNonEmpty(pool.name, 'pool name');

  const lines: string[] = [
    ...scriptHeader(),
    'configure terminal',
    '!',
  ];

  // IOS requirement: all excluded-address statements MUST precede pool definitions
  for (const pool of p.pools) {
    for (const range of (pool.excludedRanges ?? []))
      lines.push(`ip dhcp excluded-address ${range.start} ${range.end}`);
  }

  const hasExclusions = p.pools.some(pool => (pool.excludedRanges ?? []).length > 0);
  if (hasExclusions) lines.push('!');

  for (const pool of p.pools) {
    lines.push(`ip dhcp pool ${pool.name}`);
    lines.push(` network ${pool.network} ${pool.mask}`);
    if (pool.defaultGateway) lines.push(` default-router ${pool.defaultGateway}`);
    if (pool.dnsServers && pool.dnsServers.length > 0)
      lines.push(` dns-server ${pool.dnsServers.join(' ')}`);
    if (pool.domainName) lines.push(` domain-name ${pool.domainName}`);
    if (pool.leaseTime)
      lines.push(` lease ${pool.leaseTime.days} ${pool.leaseTime.hours} ${pool.leaseTime.minutes}`);
    lines.push('!');
  }

  lines.push('end');

  return build('DHCP Pool Configuration', lines, []);
}

// ─── Public API ──────────────────────────────────────────────────────────────

export function generateCiscoScript(params: CiscoScriptParams): GeneratedScript {
  switch (params.type) {
    case 'interface-basic':  return interfaceBasic(params);
    case 'interface-trunk':  return interfaceTrunk(params);
    case 'ospf-basic':       return ospfBasic(params);
    case 'static-routes':    return staticRoutes(params);
    case 'acl-extended':     return aclExtended(params);
    case 'vlan-config':      return vlanConfig(params);
    case 'dhcp-pool':        return dhcpPool(params);
  }
}
